/// Severity levels for knee monitoring alerts.
enum AlertSeverity { info, warning, critical }

/// Types of alerts the analysis engine can emit.
enum AlertType { angleThreshold, suddenMovement, mlPrediction }

/// A single alert generated by [KneeAnalysisService].
class KneeAlert {
  const KneeAlert({
    required this.type,
    required this.severity,
    required this.title,
    required this.message,
    required this.triggerValue,
    required this.thresholdValue,
    required this.timestamp,
    this.dismissed = false,
  });

  final AlertType type;
  final AlertSeverity severity;
  final String title;
  final String message;

  /// The angle or speed value that triggered this alert.
  final double triggerValue;

  /// The configured threshold that was breached.
  final double thresholdValue;

  final DateTime timestamp;
  final bool dismissed;

  KneeAlert copyWith({bool? dismissed}) {
    return KneeAlert(
      type: type,
      severity: severity,
      title: title,
      message: message,
      triggerValue: triggerValue,
      thresholdValue: thresholdValue,
      timestamp: timestamp,
      dismissed: dismissed ?? this.dismissed,
    );
  }
}
