// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter_dotenv/flutter_dotenv.dart' as dotenv;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static String _required(String key) {
    final value = dotenv.env[key];
    if (value == null || value.isEmpty) {
      throw StateError('Missing required Firebase environment variable: $key');
    }
    return value;
  }

  static String? _optional(String key) {
    final value = dotenv.env[key];
    if (value == null || value.isEmpty) {
      return null;
    }
    return value;
  }

  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static final FirebaseOptions web = FirebaseOptions(
    apiKey: _required('FIREBASE_WEB_API_KEY'),
    appId: _required('FIREBASE_WEB_APP_ID'),
    messagingSenderId: _required('FIREBASE_WEB_MESSAGING_SENDER_ID'),
    projectId: _required('FIREBASE_WEB_PROJECT_ID'),
    authDomain: _required('FIREBASE_WEB_AUTH_DOMAIN'),
    databaseURL: _required('FIREBASE_WEB_DATABASE_URL'),
    storageBucket: _required('FIREBASE_WEB_STORAGE_BUCKET'),
    measurementId: _optional('FIREBASE_WEB_MEASUREMENT_ID'),
  );

  static final FirebaseOptions android = FirebaseOptions(
    apiKey: _required('FIREBASE_ANDROID_API_KEY'),
    appId: _required('FIREBASE_ANDROID_APP_ID'),
    messagingSenderId: _required('FIREBASE_ANDROID_MESSAGING_SENDER_ID'),
    projectId: _required('FIREBASE_ANDROID_PROJECT_ID'),
    databaseURL: _required('FIREBASE_ANDROID_DATABASE_URL'),
    storageBucket: _required('FIREBASE_ANDROID_STORAGE_BUCKET'),
  );

  static final FirebaseOptions ios = FirebaseOptions(
    apiKey: _required('FIREBASE_IOS_API_KEY'),
    appId: _required('FIREBASE_IOS_APP_ID'),
    messagingSenderId: _required('FIREBASE_IOS_MESSAGING_SENDER_ID'),
    projectId: _required('FIREBASE_IOS_PROJECT_ID'),
    databaseURL: _required('FIREBASE_IOS_DATABASE_URL'),
    storageBucket: _required('FIREBASE_IOS_STORAGE_BUCKET'),
    iosBundleId: _optional('FIREBASE_IOS_BUNDLE_ID'),
  );

  static final FirebaseOptions macos = FirebaseOptions(
    apiKey: _required('FIREBASE_MACOS_API_KEY'),
    appId: _required('FIREBASE_MACOS_APP_ID'),
    messagingSenderId: _required('FIREBASE_MACOS_MESSAGING_SENDER_ID'),
    projectId: _required('FIREBASE_MACOS_PROJECT_ID'),
    databaseURL: _required('FIREBASE_MACOS_DATABASE_URL'),
    storageBucket: _required('FIREBASE_MACOS_STORAGE_BUCKET'),
    iosBundleId: _optional('FIREBASE_MACOS_BUNDLE_ID'),
  );

  static final FirebaseOptions windows = FirebaseOptions(
    apiKey: _required('FIREBASE_WINDOWS_API_KEY'),
    appId: _required('FIREBASE_WINDOWS_APP_ID'),
    messagingSenderId: _required('FIREBASE_WINDOWS_MESSAGING_SENDER_ID'),
    projectId: _required('FIREBASE_WINDOWS_PROJECT_ID'),
    authDomain: _required('FIREBASE_WINDOWS_AUTH_DOMAIN'),
    databaseURL: _required('FIREBASE_WINDOWS_DATABASE_URL'),
    storageBucket: _required('FIREBASE_WINDOWS_STORAGE_BUCKET'),
    measurementId: _optional('FIREBASE_WINDOWS_MEASUREMENT_ID'),
  );
}
