// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDcQxqLclf2iMmc1-JYFT_DdXs9sw-v834',
    appId: '1:388921890495:web:42081ccea8c9316b7f580a',
    messagingSenderId: '388921890495',
    projectId: 'gopalproject-77869',
    authDomain: 'gopalproject-77869.firebaseapp.com',
    databaseURL: 'https://gopalproject-77869-default-rtdb.firebaseio.com',
    storageBucket: 'gopalproject-77869.firebasestorage.app',
    measurementId: 'G-21YT891S9X',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAzKJWXSMDF5FddFAjxua411-jTa8Agwyc',
    appId: '1:388921890495:android:73a0884622430e0f7f580a',
    messagingSenderId: '388921890495',
    projectId: 'gopalproject-77869',
    databaseURL: 'https://gopalproject-77869-default-rtdb.firebaseio.com',
    storageBucket: 'gopalproject-77869.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyABI_2X3ZT0dUKhJTO-Hvhyt9pShxySHBA',
    appId: '1:388921890495:ios:ef7f0413efb01ff87f580a',
    messagingSenderId: '388921890495',
    projectId: 'gopalproject-77869',
    databaseURL: 'https://gopalproject-77869-default-rtdb.firebaseio.com',
    storageBucket: 'gopalproject-77869.firebasestorage.app',
    iosBundleId: 'com.example.gopalApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyABI_2X3ZT0dUKhJTO-Hvhyt9pShxySHBA',
    appId: '1:388921890495:ios:ef7f0413efb01ff87f580a',
    messagingSenderId: '388921890495',
    projectId: 'gopalproject-77869',
    databaseURL: 'https://gopalproject-77869-default-rtdb.firebaseio.com',
    storageBucket: 'gopalproject-77869.firebasestorage.app',
    iosBundleId: 'com.example.gopalApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDcQxqLclf2iMmc1-JYFT_DdXs9sw-v834',
    appId: '1:388921890495:web:47a3860c984d62ab7f580a',
    messagingSenderId: '388921890495',
    projectId: 'gopalproject-77869',
    authDomain: 'gopalproject-77869.firebaseapp.com',
    databaseURL: 'https://gopalproject-77869-default-rtdb.firebaseio.com',
    storageBucket: 'gopalproject-77869.firebasestorage.app',
    measurementId: 'G-GV3TQDC992',
  );
}
